### ISSUE TITLE
Resonate's Roadmap

### ISSUE THREAD

**Issue by dtornow** [resonatehq/resonate#131]
This roadmap represents our current plans for Resonate, which may evolve based on user feedback and changing needs. We welcome open dialogue around Resonate's direction.

## Product Features

Over the next few months, we plan to expand Resonate's features and capabilities in phases:

### Phase 1: Coordination 

During this phase, we aim to standardize durable async • await as the fundamental building block for coordinating asynchronous operations in applications.

- [x] #132  
- [x] #139 
- [x] #140 
- [ ] #133 

### Phase 2: Integration

During this phase, we aim to implement and introduce the **durable event loop**. This turns Resonate into an integration point that can coordinate end-to-end operations across different systems with different APIs.
- [ ]  etc.

#### Reliability

We are investing in robust quality assurance testing & security protections to deliver fault-tolerant and secure OSS infrastructure.

- [ ] includes quality assurance (dst, test harness, fault injection)
- [ ] includes signing artifacts with sigstore
- [ ] etc.

#### Developer Experience

We want to enable creators and developers to build on Resonate as easily as possible with clear documentation, open APIs, and a supportive community.

- [ ] includes dead simple products
- [ ] includes docs
- [ ] includes building in public (via twitter, GitHub and technical blogs, etc.)
- [ ] includes community building (via slack, community calls, office hours, durable execution university, etc.)
- [ ] includes ecosystem efforts

#### Scale

As an emerging platform, ensuring Resonate can grow sustainably - without performance degradation or exclusions - is a priority across our stack.

- [ ] etc.

**Comment by dfarr** [comment]
Please follow the resonate roadmap [here](https://github.com/orgs/resonatehq/projects/5/views/1?layout=board) for roadmap updates.

**Comment by khos2ow** [comment]
@dfarr the roadmap project board you linked above is public but none of the items in `No Status` are publicly visible! Is this intentional or just a GitHub configuration issue? It'd be nice to actually be able to see the roadmap items.

**Comment by dfarr** [comment]
> @dfarr the roadmap project board you linked above is public but none of the items in `No Status` are publicly visible! Is this intentional or just a GitHub configuration issue? It'd be nice to actually be able to see the roadmap items.

I have made the underlying repo public, let me see if you can see the roadmap now?

**Comment by khos2ow** [comment]
Yep, that did it! I feel like there's an enhancement proposal to github is lying somewhere down there!
